name: Build LaTeX document
on: 
  push:
 
    
jobs:
    Build-LaTeX-Doc:
      runs-on: ubuntu-latest
      steps:
        - name: Set up Git Repository
          uses: actions/checkout@v2
          
        - name: Compile LaTeX Doc
          id: compile-doc
          uses: xu-cheng/latex-action@v2
          with:
            root_file: main.tex
